config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  get 'users/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <% if user_signed_in? %>
          <strong><%= link_to current_user.email, users_show_path %></strong>
          <%= link_to 'ぷろふ変更', edit_user_registration_path %>
          <%= link_to 'ろぐあうと', destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to '登録する', new_user_registration_path %>
          <%= link_to 'ログイン', new_user_session_path %>
        <% end %>
      </nav>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>ようこそ</h1>
<p>トップページっす</p>

app/views/users/show.html.erb
<h1><%= current_user.id %>だな</h1>
<p>お前のページだ</p>